
const pageKey=document.body.dataset.page||'home';
function storeKey(id){return `karate:${pageKey}:${id}`}
function parseSec(txt){for(const n of [180,120,90,75,60,45,40,30,20,15]){if((txt||'').includes(String(n))) return n;} return 45;}
function setCount(txt){const m=(txt||'').match(/^(\d+)\s*x/); if(m) return Math.min(Math.max(parseInt(m[1],10),1),6); if((txt||'').includes('2 voltas')) return 2; return 1;}
function init(){document.querySelectorAll('.item').forEach((card,idx)=>{const id=card.dataset.id||String(idx); const saved=JSON.parse(localStorage.getItem(storeKey(id))||'[]'); const btns=card.querySelectorAll('.setbtn'); btns.forEach((b,i)=>{if(saved[i]) b.classList.add('on'); b.addEventListener('click',()=>{b.classList.toggle('on'); const state=[...btns].map(x=>x.classList.contains('on')); localStorage.setItem(storeKey(id), JSON.stringify(state)); card.classList.toggle('done', state.length && state.every(Boolean));});}); card.classList.toggle('done', saved.length && saved.every(Boolean));}); document.querySelectorAll('.timerbtn').forEach(btn=>btn.addEventListener('click',()=>startTimer(parseInt(btn.dataset.seconds||'45',10)))); document.querySelectorAll('.reset-all').forEach(btn=>btn.addEventListener('click', resetWorkout)); document.getElementById('closeTimer')?.addEventListener('click', closeTimer);}
let intv=null; function startTimer(sec){clearInterval(intv); const box=document.querySelector('.timer'); const value=document.getElementById('timerValue'); let left=sec; box.classList.add('show'); value.textContent=left+'s'; intv=setInterval(()=>{left--; value.textContent=left+'s'; if(left<=0){clearInterval(intv); value.textContent='vai!'; if(navigator.vibrate) navigator.vibrate([180,80,180]);}},1000);} function closeTimer(){clearInterval(intv); document.querySelector('.timer')?.classList.remove('show');}
function resetWorkout(){if(!confirm('Zerar marcações deste treino?')) return; Object.keys(localStorage).forEach(k=>{if(k.startsWith(`karate:${pageKey}:`)) localStorage.removeItem(k);}); document.querySelectorAll('.setbtn').forEach(b=>b.classList.remove('on')); document.querySelectorAll('.item').forEach(c=>c.classList.remove('done'));}
document.addEventListener('DOMContentLoaded', init);
